module.exports = {
  // FETCH_WEATHERITEMINFO: 'FETCH_WEATHERITEMINFO',
  RECEIVE_WEATHERITEMINFO: 'RECEIVE_WEATHERITEMINFO',
  // FETCH_WEATHERCITY: 'FETCH_WEATHERCITY',
  RECEIVE_WEATHERCITY: 'RECEIVE_WEATHERCITY'
}
